# basic
title: Y大壮博客
subtitle: 学习笔记
favicon: https://oss-yaodz-source.oss-cn-beijing.aliyuncs.com/Yaodz-Blog/logo_96x96.png

# avatar: images/avatar.png
# banner_small: images/banner-small.png
# banner_large: images/banner-large.png
logo: https://oss-yaodz-source.oss-cn-beijing.aliyuncs.com/Yaodz-Blog/logo.svg

# disqus
#disqus_shortname: drakeleung

highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# nav #
nav:
  "主页" : .
  "归档" : archives
  "关于": about
  # rss: atom.xml

# hexo-renderer-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Default post title
default_post_title: Untitled

# social
social:
  github: https://github.com/YaoJianqun
  # weibo: http://weibo.com/10010800
  # mail: mailto:767060568@qq.com
  # twitter: https://twitter.com/GallenHu

# widget
#   title: 标题
#   content: 内容
widget:
  title: 关于本站
  content: <ul><li><a href="https://github.com/GallenHu/hexo-theme-Daily/wiki">如何自定义这里的内容(配置教程)?</a></li></ul>

footer: Powered by <a href="https://hexo.io/" target="_blank">Hexo</a> with Theme <a href="https://github.com/GallenHu/hexo-theme-Daily" target="_blank">Daily</a>
